from typing import Protocol, Optional
from uuid import UUID

class RegistrationAuditContract(Protocol):
    async def record_registration_started(self, email: str) -> None: ...
    async def record_registration_success(self, user_id: UUID) -> None: ...
    async def record_registration_failed(self, email: str, reason: str) -> None: ...
    async def record_duplicate_email(self, email: str) -> None: ...
    async def record_duplicate_username(self, username: str) -> None: ...
    async def record_weak_password(self, email: str) -> None: ...
    async def record_email_dispatch_failure(self, user_id: UUID) -> None: ...
