from typing import Protocol

class TokenAuditContract(Protocol):
    def record_issue(self, token_type: str, jti: str, subject: str) -> None: ...
    def record_refresh(self, old_jti: str, new_jti: str) -> None: ...
    def record_rotation(self, old_jti: str, new_jti: str) -> None: ...
    def record_blacklist(self, jti: str, reason: str) -> None: ...
    def record_revoke(self, jti: str, reason: str) -> None: ...
    def record_provider(self, token_type: str, provider_name: str) -> None: ...
