from typing import Protocol, Optional

class TokenCacheLayer(Protocol):
    def set_token(self, jti: str, data: dict, ttl_seconds: int) -> None: ...
    def get_token(self, jti: str) -> Optional[dict]: ...
    def invalidate_token(self, jti: str) -> None: ...
    def add_to_blacklist(self, jti: str, ttl_seconds: int) -> None: ...
    def is_blacklisted(self, jti: str) -> bool: ...
