from typing import Protocol, Dict, Any, Optional

class TokenProvider(Protocol):
    def create_token(self, subject: str, token_type: str, custom_claims: Optional[Dict[str, Any]] = None) -> Any:
        ...
    def decode_token(self, token: str) -> Any:
        ...
    def validate_token(self, token: str, expected_type: Optional[str] = None) -> Any:
        ...
    def revoke_token(self, token: str) -> bool:
        ...
    def refresh_token(self, refresh_token: str) -> Any:
        ...
    def verify_signature(self, token: str) -> Any:
        ...
    def extract_claims(self, payload: Dict[str, Any]) -> Any:
        ...
