from typing import Protocol
from uuid import UUID

class IdentityAuditContract(Protocol):
    async def record_identity_lookup(self, identifier: str, resolved: bool, duration_ms: int) -> None: ...
    async def record_identity_validation(self, identity_id: UUID, success: bool, duration_ms: int) -> None: ...
    async def record_identity_failure(self, identity_id: UUID, reason: str) -> None: ...
    async def record_identity_cache(self, identity_id: UUID, hit: bool) -> None: ...
