from typing import Protocol, Optional
from uuid import UUID

class LoginAuditContract(Protocol):
    async def record_login_success(self, user_id: UUID, ip_address: Optional[str]) -> None: ...
    async def record_login_failed(self, identifier: str, reason: str, ip_address: Optional[str]) -> None: ...
    async def record_logout(self, user_id: UUID, session_id: UUID) -> None: ...
    async def record_token_refresh(self, user_id: UUID) -> None: ...
    async def record_session_created(self, session_id: UUID) -> None: ...
