from typing import Protocol

class AuthAuditContract(Protocol):
    def record_start(self, correlation_id: str, provider: str) -> None: ...
    def record_success(self, correlation_id: str, user_id: str) -> None: ...
    def record_failure(self, correlation_id: str, reason: str) -> None: ...
    def record_challenge(self, correlation_id: str, challenge_type: str) -> None: ...
    def record_provider(self, correlation_id: str, provider: str) -> None: ...
    def record_policy(self, correlation_id: str, policy_name: str, passed: bool) -> None: ...
    def record_risk(self, correlation_id: str, risk_score: int) -> None: ...
