from typing import Protocol, Dict, Any

class ChallengeEngineInterface(Protocol):
    def issue_challenge(self, challenge_type: str, user_id: str) -> Dict[str, Any]: ...
    def verify_challenge(self, challenge_id: str, response: Any) -> bool: ...
