from typing import Protocol, Dict, Any

class RiskEvaluationInterface(Protocol):
    def evaluate_device(self, device_context: Any) -> int: ...
    def evaluate_velocity(self, user_id: str, ip_address: str) -> int: ...
    def check_impossible_travel(self, user_id: str, location_context: Any) -> bool: ...
    def calculate_behavior_score(self, user_id: str, context: Any) -> int: ...
    def compute_aggregate_risk(self, context: Any) -> int: ...
